---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  csslint:
    enabled: true
  fixme:
    enabled: true
  method-count:
    config:
      threshold: 45
  phpcodesniffer:
    enabled: true
    checks:
      Generic Files LineLength TooLong:
        enabled: false
    exclude_paths:
    - "database/seeds/*"
    - "database/migrations/*"
  phpmd:
    enabled: true
    exclude_paths:
    - "database/migrations/*"
    checks:
      Naming/ShortVariable:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
      CleanCode/StaticAccess:
          enabled: false

ratings:
  paths:
  - "**.css"
  - "**.php"
  - "**.inc"
languages:
   PHP: true
   JavaScript: true
exclude_paths:
- "vendor/**/*"
- "tests/**/*"
- "tests/*"
- "bootstrap/autoload.php"
