---
version: "2"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: true
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  csslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
        - inc
      rulesets: "cleancode,controversial,design,naming,unusedcode,phpmd.xml"
exclude_paths:
- "vendor/**/*"
- "tests/**/*"
- "tests/*"
- "bootstrap/autoload.php"
