---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  csslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Naming/ShortMethodName:
        exclude_paths:
        - "database/migrations/*"
ratings:
  paths:
  - "**.css"
  - "**.php"
  - "**.inc"
languages:
   PHP: true
   JavaScript: true
exclude_paths:
- "vendor/**/*"
- "tests/**/*"
- "tests/*"
