language: php

php:
  - 7.1

before_install:
  - sudo aptitude -y -q install ffmpeg

before_script:
  - mv .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter

notifications:
  email:
    recipients:
      - leandro.jdl@gmail.com
    on_success: change
    on_failure: change